### ISSUE TITLE
A lookup table is not needed

### ISSUE THREAD

**Issue by conradev** [valeriomazzeo/NSString-Emoji#1]
There is a better way to approach this, using `CFStringTransform` and [`kCFStringTransformToUnicodeName`](http://developer.apple.com/library/ios/#documentation/CoreFoundation/Reference/CFMutableStringRef/Reference/reference.html%23//apple_ref/doc/uid/20001504-CH2g-SW19).

**Comment by valeriomazzeo** [comment]
from http://nshipster.com/cfstringtransform/

> Name Unicode Characters
> kCFStringTransformToUnicodeName allows you to determine the Unicode standard name for special characters, including Emoji. For instance, (github doesn't allow me to post those unicode chars :() becomes "{SHEEP} {DASH SYMBOL} {SPARKLES}".

So apparently the standard unicode names do not match the emoji cheat sheet name.
